ALTER TABLE ai_queries ADD COLUMN version BIGINT NOT NULL DEFAULT 0;
ALTER TABLE ai_answers ADD COLUMN version BIGINT NOT NULL DEFAULT 0;
ALTER TABLE ingestion_runs ADD COLUMN version BIGINT NOT NULL DEFAULT 0;
